# List of the api and their request

### fetch all the tickets
GET http://localhost:8000/api/v1/

### add new tickets
POST http://localhost:8000/api/v1/
Content-Type: application/json

{
   "task": "Singing",
    "hr": 50
}

### update tickets
PATCH http://localhost:8000/api/v1/
Content-Type: application/json



{
    "id":"61296ff577f45f3add132b98",
    "todo":false
}

### delet tickets
DELETE http://localhost:8000/api/v1/
Content-Type: application/json

{
    "id":"61296676fb71a4656d7a579e"
}